env:
  browser: true
  es2021: true
  node: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  no-console: 0
  semi: [error, never]
  arrow-parens: [error, as-needed, { requireForBlockBody: true }]
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
